// ==========================================
// CATÁLOGO DE ITENS INICIAIS — CRIAÇÃO DE PERSONAGEM
// ==========================================
// Pool fixo de itens que o jogador pode escolher ao criar o personagem.
// LIMITE_ITENS_INICIAIS define quantos itens distintos podem ser escolhidos
// (arma/armadura contam igual a consumíveis — sem sistema de peso/carga no motor hoje).

export const LIMITE_ITENS_INICIAIS = 3;

export const ITENS_INICIAIS = [
  {
    chave: "lamina_curta",
    nome: "Lâmina Curta",
    tipo: "arma",
    raridade: "comum",
    dano_ou_efeito: "1d6",
    propriedades: "leve, finesse",
    peso: "1 kg",
    valor: "15 po",
    descricao: "Uma lâmina simples e equilibrada, fácil de manejar em combate corpo a corpo.",
    habilidade_tematica: null,
  },
  {
    chave: "pistola_de_pulso",
    nome: "Pistola de Pulso",
    tipo: "arma",
    raridade: "comum",
    dano_ou_efeito: "1d8",
    propriedades: "à distância (18m), energia",
    peso: "1.5 kg",
    valor: "40 po",
    descricao: "Arma compacta que dispara pulsos de energia concentrada.",
    habilidade_tematica: null,
  },
  {
    chave: "machado_pesado",
    nome: "Machado Pesado",
    tipo: "arma",
    raridade: "comum",
    dano_ou_efeito: "1d10",
    propriedades: "pesado, duas mãos",
    peso: "4 kg",
    valor: "30 po",
    descricao: "Um machado bruto, lento mas devastador.",
    habilidade_tematica: null,
  },
  {
    chave: "armadura_leve",
    nome: "Armadura de Couro Reforçado",
    tipo: "armadura",
    raridade: "comum",
    dano_ou_efeito: null,
    propriedades: "CA base 12, leve",
    peso: "5 kg",
    valor: "45 po",
    descricao: "Couro curtido reforçado com placas metálicas nas juntas.",
    habilidade_tematica: null,
  },
  {
    chave: "armadura_pesada",
    nome: "Placas de Liga Negra",
    tipo: "armadura",
    raridade: "incomum",
    dano_ou_efeito: null,
    propriedades: "CA base 15, pesada, -3m deslocamento",
    peso: "12 kg",
    valor: "120 po",
    descricao: "Armadura de placas forjadas em liga metálica escura, comum entre mercenários de Vexon.",
    habilidade_tematica: null,
  },
  {
    chave: "pocao_cura",
    nome: "Poção de Cura",
    tipo: "consumivel",
    raridade: "comum",
    dano_ou_efeito: "1d8+4",
    propriedades: "cura, consumível",
    peso: "0.5 kg",
    valor: "50 po",
    descricao: "Um frasco de líquido rubro que acelera a regeneração celular.",
    habilidade_tematica: null,
  },
  {
    chave: "kit_ferramentas",
    nome: "Kit de Ferramentas de Ladrão",
    tipo: "ferramenta",
    raridade: "comum",
    dano_ou_efeito: null,
    propriedades: "furtividade, arrombamento",
    peso: "1 kg",
    valor: "25 po",
    descricao: "Gazuas, espelhos pequenos e ferramentas de precisão.",
    habilidade_tematica: null,
  },
  {
    chave: "kit_medico",
    nome: "Kit Médico de Campo",
    tipo: "ferramenta",
    raridade: "comum",
    dano_ou_efeito: null,
    propriedades: "cura de emergência, estabiliza aliados caídos",
    peso: "2 kg",
    valor: "35 po",
    descricao: "Bandagens, antissépticos e um estabilizador celular portátil.",
    habilidade_tematica: null,
  },
  {
    chave: "capa_furtiva",
    nome: "Capa de Fibra Sombria",
    tipo: "acessorio",
    raridade: "incomum",
    dano_ou_efeito: null,
    propriedades: "vantagem em furtividade em ambientes urbanos",
    peso: "1 kg",
    valor: "60 po",
    descricao: "Tecido tecido com fibras que absorvem luz, dificultando ser visto nas sombras.",
    habilidade_tematica: null,
  },
  {
    chave: "amuleto_sorte",
    nome: "Amuleto de Sorte Antiga",
    tipo: "acessorio",
    raridade: "rara",
    dano_ou_efeito: null,
    propriedades: "item de valor sentimental, sem efeito mecânico",
    peso: "0.1 kg",
    valor: "10 po",
    descricao: "Um pequeno amuleto gasto, passado de geração em geração. Ninguém sabe mais de onde veio.",
    habilidade_tematica: null,
  },
];

export function getItemInicial(chave) {
  return ITENS_INICIAIS.find((i) => i.chave === chave) ?? null;
}
